# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: required
r:
  - release
  - devel
env:
  - JULIA_URL: "https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.0-linux-x86_64.tar.gz"
before_install:
  - mkdir -p mkdir $HOME/julia
  - wget $JULIA_URL -O $HOME/julia/julia.tar.gz
  - tar -xzvf $HOME/julia/julia.tar.gz
  - mv $(tar tzf $HOME/julia/julia.tar.gz | head -1 | sed -e 's/\/.*//') julia
  - export PATH=$PATH:/$HOME/julia/julia/bin
script:
- R CMD build .
- R CMD check *tar.gz
cache: packages
