# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: required
r:
  - release
  - devel
env:
  - JULIA_URL: "https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.0-linux-x86_64.tar.gz"
before_install:
  - wget $JULIA_URL -O /tmp/julia.tar.gz
  - tar -xzvf /tmp/julia.tar.gz -C /tmp
  - mv /tmp/$(tar tzf /tmp/julia.tar.gz | head -1 | sed -e 's/\/.*//') /$HOME/julia
  - export PATH=$PATH:/$HOME/julia
script:
- R CMD build .
- R CMD check *tar.gz
cache: packages
